export default {
    legacy: false,
    locale: 'en',
    fallbackLocale: 'en',
    messages: {
        en: {
            varly: 'Varly',
            // Navigation
            support: 'Support',
            workspace: 'Workspace',
            switch_language: 'Switch Language',
            follow_on_twitter: 'Follow on Twitter',
            sponsor_on_github: 'Sponsor on Github',
            recent_projects: 'Recent Projects',
            start_new_project: 'Start New Project',
            open_current_project: 'Open Current Project',
            project: 'Project',
            layer_setup: 'Layer Setup',
            build_settings: 'Build Settings',
            run: 'Preview & Generate',
            next: 'Next',
            // Buttons
            close: 'Close',
            export_gif: 'Export GIF',
            open_layers_folder: 'Open Layers Folder',
            select_output_folder: 'Select Output Folder',
            generate_collection: 'Generate Collection',
            // Forms
            collection_name: 'Collection name',
            collection_description: 'Collection Descriptions',
            collection_size: 'Collection Size',
            layer_width: 'Layer Width',
            layer_height: 'Layer Height',
            // Page prompts
            no_preview_yet: 'No Preview Yet',
            ready_to_run: 'You are ready to generate your beautiful NFT collection🚀',
            get_started_by_opening_your_layers_folder: 'Get started by opening your layers folder',
            // Dialog prompts
            confirm_start_new_project_title: 'Are you sure you want to start a new project?',
            confirm_start_new_project_message: 'Your changes will be discarded unless you save the current project.',
        },
        es: {
            varly: 'Varly',
            // Navigation
            support: 'Apoyo',
            workspace: 'Espacio',
            switch_language: 'Cambia Idioma',
            follow_on_twitter: 'Síguenos en Twitter',
            sponsor_on_github: 'Patrocinanos en GitHub',
            recent_projects: 'Proyectos Recientes',
            start_new_project: 'Crear Proyecto Nuevo',
            open_current_project: 'Abre Proyecto Activo',
            project: 'Proyecto',
            layer_setup: 'Configuración de Capas',
            build_settings: 'Ajustes de Construcción',
            run: 'Revisar y Correr',
            next: 'Sígue',
            // Buttons
            close: 'Close',
            export_gif: 'Export GIF',
            open_layers_folder: 'Abrir Carpeta de Capas',
            select_output_folder: 'Seleccionar Carpeta de Producción',
            generate_collection: 'Generar la Colección',
            // Forms
            collection_name: 'Nombre de colección',
            collection_description: 'Descripcion de colección',
            collection_size: 'Cantidad de piezas',
            layer_width: 'Ancho de capas',
            layer_height: 'Altura de capas',
            // Page prompts
            no_preview_yet: 'Todavía no hay vista previa',
            ready_to_run: 'You are ready to generate your beautiful NFT collection🚀',
            get_started_by_opening_your_layers_folder: 'Inicia tu proyecto abriendo la carpeta de tu capas',
            // Dialog prompts
            confirm_start_new_project_title: 'Estas seguro que quieres iniciar otro proyecto nuevo?',
            confirm_start_new_project_message: 'Perderas el trabajo que has echo en el proyecto presente.',
        },
        fa: {
            varly: 'Varly',
            // Navigation
            support: 'Support',
            workspace: 'Workspace',
            switch_language: 'Switch Language',
            follow_on_twitter: 'Follow on Twitter',
            sponsor_on_github: 'Sponsor on Github',
            recent_projects: 'Recent Projects',
            start_new_project: 'Start New Project',
            open_current_project: 'Open Current Project',
            project: 'Project',
            layer_setup: 'Layer Setup',
            build_settings: 'Build Settings',
            run: 'Preview & Generate',
            next: 'Next',
            // Buttons
            close: 'Close',
            export_gif: 'Export GIF',
            open_layers_folder: 'Open Layers Folder',
            select_output_folder: 'Select Output Folder',
            generate_collection: 'Generate Collection',
            // Forms
            collection_name: 'Collection name',
            collection_description: 'Collection Descriptions',
            collection_size: 'Collection Size',
            layer_width: 'Layer Width',
            layer_height: 'Layer Height',
            // Page prompts
            no_preview_yet: 'No Preview Yet',
            ready_to_run: 'You are ready to generate your beautiful NFT collection🚀',
            get_started_by_opening_your_layers_folder: 'Get started by opening your layers folder',
            // Dialog prompts
            confirm_start_new_project_title: 'Are you sure you want to start a new project?',
            confirm_start_new_project_message: 'Your changes will be discarded unless you save the current project.',
        },
    }
}
