// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
window.wailsbindings = {"main":{"App":{"EncodeImage":{"name":"main.App.EncodeImage","inputs":[{"type":"string"}],"outputs":[{"type":"string"}]},"GenerateCollectionFromConfig":{"name":"main.App.GenerateCollectionFromConfig","inputs":[{"type":"nft.NewCollectionConfig"}]},"GetApplicationDocumentsDirectory":{"name":"main.App.GetApplicationDocumentsDirectory","outputs":[{"type":"string"}]},"OpenDirectoryDialog":{"name":"main.App.OpenDirectoryDialog","outputs":[{"type":"string"}]},"OpenFileDialog":{"name":"main.App.OpenFileDialog","outputs":[{"type":"string"}]},"ReadLayers":{"name":"main.App.ReadLayers","inputs":[{"type":"string"}],"outputs":[{"type":"fs.CollectionConfig"}]},"Save":{"name":"main.App.Save","inputs":[{"type":"string"},{"type":"string"}],"outputs":[{"type":"bool"}]},"SaveFileDialog":{"name":"main.App.SaveFileDialog","outputs":[{"type":"string"}]},"UploadCollection":{"name":"main.App.UploadCollection","outputs":[{"type":"string"}]}}}};
const go = {
  "main": {
    "App": {
      /**
       * EncodeImage
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "EncodeImage": (arg1) => {
        return window.go.main.App.EncodeImage(arg1);
      },
      /**
       * GenerateCollectionFromConfig
       * @param {NewCollectionConfig} arg1 - Go Type: nft.NewCollectionConfig
       * @returns {Promise<void>} 
       */
      "GenerateCollectionFromConfig": (arg1) => {
        return window.go.main.App.GenerateCollectionFromConfig(arg1);
      },
      /**
       * GetApplicationDocumentsDirectory
       * @returns {Promise<string>}  - Go Type: string
       */
      "GetApplicationDocumentsDirectory": () => {
        return window.go.main.App.GetApplicationDocumentsDirectory();
      },
      /**
       * OpenDirectoryDialog
       * @returns {Promise<string>}  - Go Type: string
       */
      "OpenDirectoryDialog": () => {
        return window.go.main.App.OpenDirectoryDialog();
      },
      /**
       * OpenFileDialog
       * @returns {Promise<string>}  - Go Type: string
       */
      "OpenFileDialog": () => {
        return window.go.main.App.OpenFileDialog();
      },
      /**
       * ReadLayers
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<CollectionConfig>}  - Go Type: fs.CollectionConfig
       */
      "ReadLayers": (arg1) => {
        return window.go.main.App.ReadLayers(arg1);
      },
      /**
       * Save
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "Save": (arg1, arg2) => {
        return window.go.main.App.Save(arg1, arg2);
      },
      /**
       * SaveFileDialog
       * @returns {Promise<string>}  - Go Type: string
       */
      "SaveFileDialog": () => {
        return window.go.main.App.SaveFileDialog();
      },
      /**
       * UploadCollection
       * @returns {Promise<string>}  - Go Type: string
       */
      "UploadCollection": () => {
        return window.go.main.App.UploadCollection();
      },
    },
  },

};
export default go;
