// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * GenerateCollection
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<CollectionConfig>}  - Go Type: fs.CollectionConfig
       */
      "GenerateCollection": (arg1) => {
        return window.go.main.App.GenerateCollection(arg1);
      },
      /**
       * GenerateCollectionFromConfig
       * @param {NewCollectionConfig} arg1 - Go Type: nft.NewCollectionConfig
       * @returns {Promise<void>} 
       */
      "GenerateCollectionFromConfig": (arg1) => {
        return window.go.main.App.GenerateCollectionFromConfig(arg1);
      },
      /**
       * OpenDirectoryDialog
       * @returns {Promise<string>}  - Go Type: string
       */
      "OpenDirectoryDialog": () => {
        return window.go.main.App.OpenDirectoryDialog();
      },
      /**
       * OpenFileDialog
       * @returns {Promise<string>}  - Go Type: string
       */
      "OpenFileDialog": () => {
        return window.go.main.App.OpenFileDialog();
      },
      /**
       * SaveFileDialog
       * @returns {Promise<string>}  - Go Type: string
       */
      "SaveFileDialog": () => {
        return window.go.main.App.SaveFileDialog();
      },
      /**
       * UploadCollection
       * @returns {Promise<string>}  - Go Type: string
       */
      "UploadCollection": () => {
        return window.go.main.App.UploadCollection();
      },
    },
  },

};
export default go;
